package shared;

public enum TypeOfMessage {

    LOGIN,
    REGISTER,
    SEARCH_BY_TYPE,
    SEARCH_BY_PRICE,
    ERROR,
    SEARCH_BY_CONDITION,
    CREATE_ORDER,
    GET_ALL_PRODUCTS,
    CREATE_PRODUCT_FOR_SELLING,
    SUBSCRIBE_TO_TYPE,
    GET_PRODUCTS_TO_CONFIRM,
    CONFIRM_PRODUCT;
}
