package shared;

public enum TypeOfMessage {

    LOGIN,
    REGISTER,
    SEARCH_BY_TYPE,
    SEARCH_BY_PRICE,
    ERROR,
    SEARCH_BY_CONDITION,
    CREATE_ORDER,
    PRODUCTS,
    NEW_MESSAGES,
    ORDER_RESPONSE,
    CREATE_PRODUCT_FOR_SELLING;
    ORDER_RESPONSE,
    SUBSCRIBE_TO_TYPE,
    PRODUCTS_TO_CONFIRM,
    CONFIRM_PRODUCT;
}
